import os
import re
import logging
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas

logger = logging.getLogger(__name__)

class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute and render total page count
    along with running headers and footers.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        # We omit header and footer on the cover page (Page 1)
        if self._pageNumber == 1:
            return

        self.saveState()
        
        # Color definitions
        primary_color = colors.HexColor("#0F172A")  # Slate-900
        gray_600 = colors.HexColor("#4B5563")      # Gray-600
        border_color = colors.HexColor("#E5E7EB")  # Gray-200

        # Draw Running Header
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(primary_color)
        self.drawString(54, 750, "PARALEGAL AGENTIC AI OPS MANAGER")
        
        self.setFont("Helvetica", 8)
        self.setFillColor(gray_600)
        self.drawRightString(612 - 54, 750, "CONFIDENTIAL // NDA AUDIT BRIEF")
        
        self.setStrokeColor(border_color)
        self.setLineWidth(0.75)
        self.line(54, 742, 612 - 54, 742)

        # Draw Running Footer
        self.line(54, 48, 612 - 54, 48)
        self.drawString(54, 34, "Generated by autonomous Paralegal Crew (Think → Decide → Act → Observe)")
        
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(612 - 54, 34, page_text)

        self.restoreState()

def clean_text_formatting(text: str) -> str:
    """Converts standard markdown formatting to HTML-like tags for ReportLab Paragraphs."""
    if not text:
        return ""
    
    # 1. Convert bold **text** or __text__ to <b>text</b>
    text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', text)
    text = re.sub(r'__(.*?)__', r'<b>\1</b>', text)
    
    # 2. Convert italic *text* or _text_ to <i>text</i>
    text = re.sub(r'\*(.*?)\*', r'<i>\1</i>', text)
    text = re.sub(r'_(.*?)_', r'<i>\1</i>', text)
    
    # 3. Convert inline code `code` to monospaced text
    text = re.sub(r'`(.*?)`', r'<font face="Courier" size="8.5" color="#1E293B">\1</font>', text)
    
    # 4. Escape ampersands not already part of an HTML entity
    text = re.sub(r'&(?!(amp|lt|gt|quot|apos);)', r'&amp;', text)
    
    # 5. Handle simple line breaks
    text = text.replace("\n", "<br/>")
    
    return text

def parse_markdown_to_flowables(markdown_text: str, styles: dict) -> list:
    """Parses markdown text and converts it into a list of ReportLab Flowables."""
    flowables = []
    if not markdown_text:
        return flowables

    # Normalize line endings and split by double-newline blocks
    blocks = markdown_text.replace("\r\n", "\n").split("\n\n")
    
    in_code_block = False
    code_buffer = []

    for block in blocks:
        block = block.strip()
        if not block:
            continue

        # Handle Code Block Toggles
        if block.startswith("```"):
            if in_code_block:
                # Close code block
                code_content = "\n".join(code_buffer)
                code_content = code_content.replace("<", "&lt;").replace(">", "&gt;")
                flowables.append(Paragraph(f"<pre>{code_content}</pre>", styles["MarkdownCode"]))
                flowables.append(Spacer(1, 8))
                in_code_block = False
                code_buffer = []
            else:
                in_code_block = True
                # Remove the language tag if present
                lines = block.split("\n")
                if len(lines) > 1:
                    code_buffer.extend(lines[1:])
            continue
            
        if in_code_block:
            code_buffer.append(block)
            continue

        # Headers
        if block.startswith("# "):
            text = clean_text_formatting(block[2:].strip())
            flowables.append(Paragraph(text, styles["MarkdownH1"]))
            flowables.append(Spacer(1, 10))
        elif block.startswith("## "):
            text = clean_text_formatting(block[3:].strip())
            flowables.append(Paragraph(text, styles["MarkdownH2"]))
            flowables.append(Spacer(1, 8))
        elif block.startswith("### "):
            text = clean_text_formatting(block[4:].strip())
            flowables.append(Paragraph(text, styles["MarkdownH3"]))
            flowables.append(Spacer(1, 6))
        # Bullet List Items
        elif block.startswith("- ") or block.startswith("* "):
            lines = block.split("\n")
            for line in lines:
                line = line.strip()
                if line.startswith("- ") or line.startswith("* "):
                    text = clean_text_formatting(line[2:].strip())
                    flowables.append(Paragraph(text, styles["MarkdownBullet"]))
                    flowables.append(Spacer(1, 4))
            flowables.append(Spacer(1, 6))
        # Numbered List Items
        elif block[0].isdigit() and (block[1:].startswith(". ") or (len(block) > 2 and block[2:].startswith(". "))):
            lines = block.split("\n")
            for line in lines:
                line = line.strip()
                dot_idx = line.find(". ")
                if dot_idx != -1 and line[:dot_idx].isdigit():
                    num = line[:dot_idx+1]
                    text = clean_text_formatting(line[dot_idx+2:].strip())
                    flowables.append(Paragraph(f"<b>{num}</b> {text}", styles["MarkdownBody"]))
                    flowables.append(Spacer(1, 4))
            flowables.append(Spacer(1, 6))
        # Standard Paragraph
        else:
            text = clean_text_formatting(block)
            flowables.append(Paragraph(text, styles["MarkdownBody"]))
            flowables.append(Spacer(1, 8))

    return flowables

def generate_pdf_report(job, clauses: list, pdf_path: str):
    """
    Compiles a comprehensive corporate legal risk brief PDF using ReportLab.
    
    Includes:
    - Sleek Cover Page with Metadata panel & Risk Level indicator
    - Executive Summary
    - High-risk Identified Clauses Table
    - Deep Dive AI report breakdown parsed directly from the Markdown state
    """
    logger.info(f"PDF Gen: Generating report for Job {job.id} at {pdf_path}")
    
    # 1. Page template setup
    # Margins are 54pt (0.75 in). Printable width: 612 - 108 = 504pt.
    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=72,
        bottomMargin=72
    )
    
    # 2. Styling dictionary setup
    base_styles = getSampleStyleSheet()
    styles = {}
    
    # Colors
    slate_900 = colors.HexColor("#0F172A")
    slate_700 = colors.HexColor("#334155")
    slate_500 = colors.HexColor("#64748B")
    blue_600 = colors.HexColor("#2563EB")
    
    styles["CoverTitle"] = ParagraphStyle(
        "CoverTitle",
        fontName="Helvetica-Bold",
        fontSize=28,
        leading=34,
        textColor=slate_900,
        spaceAfter=10
    )
    
    styles["CoverSubtitle"] = ParagraphStyle(
        "CoverSubtitle",
        fontName="Helvetica",
        fontSize=12,
        leading=16,
        textColor=slate_500,
        spaceAfter=25
    )
    
    styles["MetaLabel"] = ParagraphStyle(
        "MetaLabel",
        fontName="Helvetica-Bold",
        fontSize=10,
        leading=13,
        textColor=slate_900
    )
    
    styles["MetaValue"] = ParagraphStyle(
        "MetaValue",
        fontName="Helvetica",
        fontSize=10,
        leading=13,
        textColor=slate_700
    )
    
    styles["MarkdownH1"] = ParagraphStyle(
        "MDH1",
        fontName="Helvetica-Bold",
        fontSize=18,
        leading=22,
        textColor=slate_900,
        spaceBefore=14,
        spaceAfter=8,
        keepWithNext=True
    )
    
    styles["MarkdownH2"] = ParagraphStyle(
        "MDH2",
        fontName="Helvetica-Bold",
        fontSize=14,
        leading=18,
        textColor=slate_900,
        spaceBefore=12,
        spaceAfter=6,
        keepWithNext=True
    )
    
    styles["MarkdownH3"] = ParagraphStyle(
        "MDH3",
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=15,
        textColor=slate_900,
        spaceBefore=10,
        spaceAfter=4,
        keepWithNext=True
    )
    
    styles["MarkdownBody"] = ParagraphStyle(
        "MDBody",
        fontName="Helvetica",
        fontSize=9.5,
        leading=14,
        textColor=slate_700,
        spaceAfter=8
    )
    
    styles["MarkdownBullet"] = ParagraphStyle(
        "MDBullet",
        fontName="Helvetica",
        fontSize=9.5,
        leading=14,
        textColor=slate_700,
        leftIndent=15,
        bulletIndent=5,
        spaceAfter=4
    )
    
    styles["MarkdownCode"] = ParagraphStyle(
        "MDCode",
        fontName="Courier",
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#1E293B"),
        backColor=colors.HexColor("#F1F5F9"),
        borderPadding=6,
        spaceAfter=8
    )

    styles["TableHeader"] = ParagraphStyle(
        "TableHeader",
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=11,
        textColor=colors.white
    )
    
    styles["TableCell"] = ParagraphStyle(
        "TableCell",
        fontName="Helvetica",
        fontSize=8.5,
        leading=11,
        textColor=slate_700
    )
    
    styles["TableCellBold"] = ParagraphStyle(
        "TableCellBold",
        fontName="Helvetica-Bold",
        fontSize=8.5,
        leading=11,
        textColor=slate_900
    )

    story = []
    
    # =========================================================================
    # COVER PAGE
    # =========================================================================
    story.append(Spacer(1, 40))
    
    # Top Accent bar
    accent_bar_data = [[""]]
    accent_bar_table = Table(accent_bar_data, colWidths=[504], rowHeights=[6])
    accent_bar_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), blue_600),
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
        ('TOPPADDING', (0,0), (-1,-1), 0),
    ]))
    story.append(accent_bar_table)
    story.append(Spacer(1, 20))
    
    # Title & Subtitle
    story.append(Paragraph("LEGAL RISK BRIEF", styles["CoverTitle"]))
    story.append(Paragraph("Automated Contract Audit & Compliance Risk Assessment Report", styles["CoverSubtitle"]))
    
    story.append(Spacer(1, 40))
    
    # Metadata Box
    filename = job.document.filename if job.document else "Unknown_NDA.pdf"
    date_str = datetime.utcnow().strftime("%B %d, %Y")
    
    # Determine risk badge styling
    risk_score = job.risk_score or 0.0
    if risk_score >= 8.0:
        risk_label = "CRITICAL RISK"
        risk_color = colors.HexColor("#EF4444")
        bg_color = colors.HexColor("#FEE2E2")
    elif risk_score >= 5.0:
        risk_label = "HIGH RISK"
        risk_color = colors.HexColor("#F97316")
        bg_color = colors.HexColor("#FFEDD5")
    elif risk_score >= 3.0:
        risk_label = "MEDIUM RISK"
        risk_color = colors.HexColor("#EAB308")
        bg_color = colors.HexColor("#FEF9C3")
    else:
        risk_label = "LOW RISK"
        risk_color = colors.HexColor("#22C55E")
        bg_color = colors.HexColor("#DCFCE7")
        
    meta_data = [
        [Paragraph("Target Contract", styles["MetaLabel"]), Paragraph(filename, styles["MetaValue"])],
        [Paragraph("Analysis Job ID", styles["MetaLabel"]), Paragraph(job.id, styles["MetaValue"])],
        [Paragraph("Date Analyzed", styles["MetaLabel"]), Paragraph(date_str, styles["MetaValue"])],
        [Paragraph("Audit Engine Status", styles["MetaLabel"]), Paragraph(job.status, styles["MetaValue"])],
        [Paragraph("Global Risk Score", styles["MetaLabel"]), Paragraph(f"<b>{risk_score}/10.0</b>", styles["MetaValue"])]
    ]
    
    meta_table = Table(meta_data, colWidths=[150, 354])
    meta_table.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('LINEBELOW', (0,0), (-1,-1), 0.5, colors.HexColor("#F1F5F9")),
    ]))
    story.append(meta_table)
    
    story.append(Spacer(1, 40))
    
    # Risk Badge Block
    badge_data = [
        [
            Paragraph(f"<font color='{risk_color.hexval()}'><b>{risk_label} ({risk_score:.1f}/10)</b></font>", styles["CoverSubtitle"]),
            Paragraph("This contract has been processed by the AI Paralegal Agent Crew. Major liabilities, indemnity clauses, and termination terms have been extracted and scored according to the risk weight database.", styles["TableCell"])
        ]
    ]
    badge_table = Table(badge_data, colWidths=[150, 354])
    badge_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (0,0), bg_color),
        ('ALIGN', (0,0), (0,0), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('TOPPADDING', (0,0), (-1,-1), 12),
        ('BOTTOMPADDING', (0,0), (-1,-1), 12),
        ('LEFTPADDING', (0,0), (-1,-1), 12),
        ('RIGHTPADDING', (0,0), (-1,-1), 12),
        ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
    ]))
    story.append(badge_table)
    
    story.append(PageBreak())
    
    # =========================================================================
    # EXECUTIVE RISK TABLE
    # =========================================================================
    story.append(Paragraph("Risk Breakdown Table", styles["MarkdownH1"]))
    story.append(Paragraph("The following table details every clause flagged as potentially high risk. Sorting priority is based on the lexicon severity weights.", styles["MarkdownBody"]))
    story.append(Spacer(1, 10))
    
    # Column Widths must sum to exactly 504 (printable width)
    # Category (80), Score (55), Page (40), details (329)
    col_widths = [80, 55, 40, 329]
    table_content = [[
        Paragraph("Category", styles["TableHeader"]),
        Paragraph("Score", styles["TableHeader"]),
        Paragraph("Page", styles["TableHeader"]),
        Paragraph("Identified Clause & Risk Explanation", styles["TableHeader"])
    ]]
    
    # Add clauses to table
    if clauses:
        for idx, c in enumerate(clauses):
            # Format risk score and color
            c_score = c.get("risk_score", 1.0)
            if c_score >= 8.0:
                score_cell_text = f"<font color='#B91C1C'><b>{c_score:.1f}</b> (Crit)</font>"
            elif c_score >= 5.0:
                score_cell_text = f"<font color='#C2410C'><b>{c_score:.1f}</b> (High)</font>"
            else:
                score_cell_text = f"<font color='#B45309'><b>{c_score:.1f}</b> (Med)</font>"
                
            clause_text = c.get("text", "")
            # Truncate clause text if it's too long
            if len(clause_text) > 180:
                clause_text = clause_text[:180] + "..."
                
            explanation = c.get("risk_explanation", "")
            
            details_html = (
                f"<b>Original Text:</b> \"<i>{clean_text_formatting(clause_text)}</i>\"<br/>"
                f"<b>Explanation:</b> {clean_text_formatting(explanation)}"
            )
            
            row = [
                Paragraph(c.get("risk_category", "General"), styles["TableCellBold"]),
                Paragraph(score_cell_text, styles["TableCell"]),
                Paragraph(str(c.get("page_num", 1)), styles["TableCell"]),
                Paragraph(details_html, styles["TableCell"])
            ]
            table_content.append(row)
    else:
        table_content.append([
            Paragraph("N/A", styles["TableCell"]),
            Paragraph("N/A", styles["TableCell"]),
            Paragraph("N/A", styles["TableCell"]),
            Paragraph("No highly hazardous clauses matching the risk lexicon were identified.", styles["TableCell"])
        ])
        
    risk_table = Table(table_content, colWidths=col_widths, repeatRows=1)
    
    # Build TableStyle list
    t_style = [
        ('BACKGROUND', (0,0), (-1,0), slate_900),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('LEFTPADDING', (0,0), (-1,-1), 6),
        ('RIGHTPADDING', (0,0), (-1,-1), 6),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
    ]
    
    # Alternating row background for readability
    if clauses:
        for idx in range(1, len(table_content)):
            if idx % 2 == 0:
                t_style.append(('BACKGROUND', (0, idx), (-1, idx), colors.HexColor("#F8FAFC")))
                
    risk_table.setStyle(TableStyle(t_style))
    story.append(risk_table)
    story.append(Spacer(1, 20))
    story.append(PageBreak())
    
    # =========================================================================
    # DETAILED AI EXECUTIVE REPORT
    # =========================================================================
    story.append(Paragraph("Detailed AI Audit & Analysis", styles["MarkdownH1"]))
    story.append(Paragraph("Below is the deep dive report compiled by the Gemini Report Agent node in the LangGraph crew.", styles["MarkdownBody"]))
    story.append(Spacer(1, 10))
    
    report_markdown = job.report_markdown or "# No Report Generated\nThe system failed to produce an executive markdown summary."
    
    # Parse markdown into Flowables
    md_flowables = parse_markdown_to_flowables(report_markdown, styles)
    story.extend(md_flowables)
    
    # 4. Build PDF using NumberedCanvas
    doc.build(story, canvasmaker=NumberedCanvas)
    logger.info(f"PDF Gen: Finished compiling Job {job.id} PDF brief.")
